#!/usr/bin/env ruby

require_relative 'lib/environment'
require_relative 'lib/argument_parser'
require_relative 'lib/interactions'

# Router:
class Jstudy
 include Interactions
 attr_reader :options

 def initialize
  @options = ArgumentParser.parse
  Environment.environment = @options[:environment] || "production"
 end

 def main

  database = Environment.database_connection

  if options[:command] == "search"
   search_term = ask("What do you want to search for?")
   search_words_for(search_term)
  elsif options[:command] == "searchenglish"
   search_term = ask("What do you want to search for?")
   searchenglish_words_for(search_term)
  elsif options[:command] == "add"
   error_messages = ArgumentParser.validate(options)
   if error_messages.empty?
    word = Word.new(options)
    word.save
    puts "A word with the kanji #{word.kanji}, onyomi #{word.onyomi}, kunyomi #{word.kunyomi}, the english translation '#{word.english}', JLPT level #{word.jlptlevel} and category '#{word.category}' was created."
   else
    puts error_messages
   end
  elsif options[:command] == "list"
   list_words()
  elsif options[:command] == "edit"
   if word = Word.find(options[:id])
    word.update(options)
    puts "Word #{word.id} now has the kanji #{word.kanji}, the onyomi #{word.onyomi}, the kunyomi #{word.kunyomi}, the english translation '#{word.english}', the JLPT level #{word.jlptlevel} and the category #{word.category}."
   else
    puts "Word #{options[:id]} couldn't be found."
   end

  elsif options[:command] == "start"
   lesson_type = start_screen_gets_lesson_type

   until(lesson_type == "v" || lesson_type == "k" || lesson_type == "q") do
    lesson_type = start_screen_gets_lesson_type
   end

   if lesson_type == "v"
    puts "let's start a vocabulary practice session, はじめましょう！"
    jlpt_level = get_jlpt_level
   elsif lesson_type == "k"
    puts "let's start a kanji practice session, はじめましょう！"
    jlpt_level = get_jlpt_level
   else lesson_type == "q"
    puts "See you next time, じゃまたね"
    exit
   end
  else
   puts "Command not implemented"
  end
 end

 def get_jlpt_level
  jlpt_level = ""
  levels = ["1", "2", "3", "4", "5"]
  until (levels.include?(jlpt_level)) do
   puts "Choose your JLPT level, 1 through 5"
   jlpt_level = $stdin.gets.chomp
  end
  puts "You chose JLPT level N#{jlpt_level}."
 end

 def start_screen_gets_lesson_type
  puts "
     ______________________________________________________________
    | ___________________________________________________________  |
    | |   _______     ______   _______ __   __  ______  __    __ | |
    | |  |__   __|   /  ___ \\ |__  ___|| |  | | | ___ \\ \\ \\  / / | |
    | |     | |      | |   \\_|   | |   | |  | | | |  | | \\ \\/ /  | |
    | |     | |  __  |  \\___     | |   | |  | | | |  | |  \\  /   | |
    | |  _  | | |__|  \\___  \\    | |   | |  | | | |  | |   | |   | |
    | | | | | |       _   \\  |   | |   | |  | | | |  | |   | |   | |
    | | | |_| |      | |__/  |   | |   | |__| | | |__/ |   | |   | |
    | | \\_____/      \\______/    |_|   \\______/ |_____/    |_|   | |
    | |__________________________________________________________| |
    |                                                              |
    |  * * * * * * * * * * *    へようこそ   * * * * * * * * * * * |
    |______________________________________________________________|

    hit v to start a vocabulary study session, k for a kanji session
                            or hit q to quit
  "
  lesson_type = $stdin.gets.chomp
  lesson_type
 end

 def list_words()
  puts "All Words:"
  puts Word.all
 end

 def search_words_for(search_term)
  puts "You asked for: #{search_term}"
  puts Word.search(search_term)
 end

 def searchenglish_words_for(search_term)
  puts "You asked for: #{search_term}"
  puts Word.searchenglish(search_term)
 end

end
jstudy = Jstudy.new()
jstudy.main()